// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GuessGuessGetData, GuessGuessGetErrors, GuessGuessGetResponses, RootGetData, RootGetResponses, WordWordGetData, WordWordGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Word
 */
export const wordWordGet = <ThrowOnError extends boolean = false>(options?: Options<WordWordGetData, ThrowOnError>) => (options?.client ?? client).get<WordWordGetResponses, unknown, ThrowOnError>({ url: '/word', ...options });

/**
 * Guess
 */
export const guessGuessGet = <ThrowOnError extends boolean = false>(options: Options<GuessGuessGetData, ThrowOnError>) => (options.client ?? client).get<GuessGuessGetResponses, GuessGuessGetErrors, ThrowOnError>({ url: '/guess', ...options });
