// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * GuessResponse
 */
export type GuessResponse = {
    /**
     * Word
     *
     * The word guessed by the player
     */
    word: string;
    /**
     * Similarity
     *
     * Cosine similarity with the daily word
     */
    similarity: number;
    /**
     * Found
     *
     * Whether the player has guessed the daily word
     */
    found: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SimilarWord
 */
export type SimilarWord = {
    /**
     * Word
     *
     * A word similar to the query
     */
    word: string;
    /**
     * Similarity
     *
     * Cosine similarity with the query word
     */
    similarity: number;
};

/**
 * SimilarWordsResponse
 */
export type SimilarWordsResponse = {
    /**
     * Words
     *
     * Top similar words ordered by similarity descending
     */
    words: Array<SimilarWord>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VocabularyResponse
 */
export type VocabularyResponse = {
    /**
     * Words
     *
     * Words eligible to be the daily word
     */
    words: Array<string>;
};

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VocabularyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/vocabulary';
};

export type VocabularyResponses = {
    /**
     * Successful Response
     */
    200: VocabularyResponse;
};

export type VocabularyResponse2 = VocabularyResponses[keyof VocabularyResponses];

export type GuessData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
    };
    url: '/guess';
};

export type GuessErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GuessError = GuessErrors[keyof GuessErrors];

export type GuessResponses = {
    /**
     * Successful Response
     */
    200: GuessResponse;
};

export type GuessResponse2 = GuessResponses[keyof GuessResponses];

export type SimilarData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
    };
    url: '/similar';
};

export type SimilarErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SimilarError = SimilarErrors[keyof SimilarErrors];

export type SimilarResponses = {
    /**
     * Successful Response
     */
    200: SimilarWordsResponse;
};

export type SimilarResponse = SimilarResponses[keyof SimilarResponses];
