// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * GuessResponse
 */
export type GuessResponse = {
    /**
     * Word
     *
     * The word guessed by the player
     */
    word: string;
    /**
     * Similarity
     *
     * Cosine similarity with the daily word
     */
    similarity: number;
    /**
     * Found
     *
     * Whether the player has guessed the daily word
     */
    found: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type WordWordGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/word';
};

export type WordWordGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GuessGuessGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
    };
    url: '/guess';
};

export type GuessGuessGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GuessGuessGetError = GuessGuessGetErrors[keyof GuessGuessGetErrors];

export type GuessGuessGetResponses = {
    /**
     * Successful Response
     */
    200: GuessResponse;
};

export type GuessGuessGetResponse = GuessGuessGetResponses[keyof GuessGuessGetResponses];
